---
- name: Install Flatpak
  include_tasks:
    file: software/flatpak.yml

- name: Install Snap
  include_tasks:
    file: software/snap.yml

- name: Install Rambox
  include_tasks:
    file: software/rambox.yml

- name: Install MPV
  include_tasks:
    file: software/mpv.yml

- name: Install Brave
  include_tasks:
    file: software/brave.yml

- name: Install Alacritty
  include_tasks:
    file: software/alacritty.yml

- name: Install Discord
  include_tasks:
    file: software/discord.yml

- name: Install Flameshot
  include_tasks:
    file: software/flameshot.yml

- name: Install Mailspring
  include_tasks:
    file: software/mailspring.yml

- name: Install Obsidian
  include_tasks:
    file: software/obsidian.yml

- name: Install ohMyZSH
  include_tasks:
    file: software/ohmyzsh.yml

- name: Install Remmina
  include_tasks:
    file: software/remmina.yml

- name: Install Signal
  include_tasks:
    file: software/signal.yml

- name: Install Spotify
  include_tasks:
    file: software/spotify.yml

- name: Install Teams
  include_tasks:
    file: software/teams.yml

- name: Install VSCodium
  include_tasks:
    file: software/vscodium.yml

- name: Install Zoom
  include_tasks:
    file: software/zoom.yml

- name: ZSH Plugins
  include_tasks:
    file: tools/zsh.yml
