---
- name: Install ZSH syntax Highlighting
  git:
      clone: yes
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
 
