---
- name: Install Alacritty
  package: alacritty
    state: present

- name: Copy Alacritty config
  copy:
    src: /base/files/alacritty
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
