---
- name: Install alacritty.
  become: true
  package:
    name:
      - alacritty


- name: Copy Alacritty config
  copy:
    src: /base/files/alacritty
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
