---
- name: Install Alacritty
  become: true
  snap:
    name: alacritty
    classic: yes
    state: present

- name: Make Alacritty Folder
  file:
    path: "{{ home }}/.config/alacritty"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775


- name: Copy Alacritty config
  copy:
    src: files/alacritty
    dest: "{{ home }}/.config/alacritty/alacritty.toml"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Make Alacritty Folder
  file:
    path: "{{ home }}/.config/alacritty/themes"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775

- name: Clone Alacritty Theme
  git:
    clone: yes
    repo: https://github.com/alacritty/alacritty-theme.git
    dest: "{{ home }}/.config/alacritty/themes"
    update: yes
