---
- name: Install alacritty.
  become: true
  package:
    name:
      - alacritty
    state: present

- name: Make NeoVIM Folder
  file:
    path: "{{ home }}/.config/alacritty"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775


- name: Copy Alacritty config
  copy:
    src: files/alacritty
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
