---
- name: Check if oh-my-zsh is already installed
  stat: path="{{ home }}/git/ohmyzsh"
  register: haziohymyzsh
 
- name: Clone oh-my-zsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ home }}/git/ohmyzsh"
    accept_hostkey: yes
    update: no
    force: no

- name: Install oh-my-zsh
  shell: |
    ZSH=~/git/oh-my-zsh && sh -c ~/git/ohmyzsh/tools/install.sh --unattended
  when: not haziohymyzsh.stat.exists

- name: Install ZSH syntax Highlighting
  git:
    clone: yes
    update: yes
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

