---
- name: Check if oh-my-zsh is already installed
  stat: path="/usr/share/oh-my-zsh"
  register: haziohymyzsh
  tags: ['ohmyzsh']

- name: Clone oh-my-zsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ home }}/git/ohmyzsh"
    accept_hostkey: yes
    update: no
    force: no

- name: Install oh-my-zsh
  shell: |
    export ZSH=""{{ home }}/git/ohmyzsh"" && \
    sh -c './install.sh --unattended'
  args:
    chdir: ""{{ home }}/git/ohmyzsh"/ohmyzsh/tools/"
  when: not haziohymyzsh.stat.exists
  tags: ['ohmyzsh']

- name: Install ZSH syntax Highlighting
  git:
    clone: yes
    update: yes
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

