---
- name: Snap
  become: true
  package:
    name:
      - snapd
    state: present

- name: Link for Classic Snap
  become: yes
  file:
    src: "/snap"
    dest: "/var/lib/snapd/snap"
    state: link