---
- name: Snap
  become: true
  package:
    name: snapd
    classic: yes  
    state: present

- name: Snap Classic Link
  become: yes
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
