---
- name: Snap
  become: true
  package:
    name: snapd
    state: present

- name: Snap Classic Link
  become: true
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  when:
    - ansible_distribution == "Archlinux"

- name: Snap Service
  become: true
  shell: |
    systemctl enable --now snapd
