---
- name: Snap
  become: true
  package:
    name:
      - snapd
    state: present

- name: Link for Classic Snap
  become: yes
  file:
    src: "/var/snap/snapd"
    dest: "/snap"
    state: link
    owner: "root"
    gid: "root"
    mode: 0755