- name: Install libvirt packages.
  become: true
  package:
    name:
      - libvirt
      - libvirt-bash-completion
      - libvirt-client
      - virt-install
      - virt-manager
    state: present


- name: Add '{{ user }}' to libvirt group.
  become: true
  user:
    name: "{{ user }}"
    groups: libvirt
    append: true