---
 - name: Clone ohmyzsh
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ home }}/git/ohmyzsh"
      update: yes

  - name: Install ohmyzsh
    shell:
      chdir: "{{ home }}/git/ohmyzsh/tools"
      executable: "{{ home }}/git/ohmyzsh/tools/install.sh"
      cmd: install.sh
