- name: software | signal | install package
  become_user: {{ user }}
  flatpak:
    name: org.signal.Signal
    method: user
    state: present
  when: signal is defined and signal == true

- name: software | signal | enable autostart
  tags: packages,flatpak,signal,workstation-packages
  file:
    src: /home/{{ user }}/.local/share/flatpak/exports/share/applications/org.signal.Signal.desktop
    dest: /home/{{ user }}/.config/autostart/org.signal.Signal.desktop
    owner: {{ user }}
    group: {{ user }}
    state: link
  when: signal is defined and signal == true