---
- name: Install Base Package
  become: true
  become_method: sudo
  package: 
    name: 
      - tmux
      - htop
      - zsh
      - neofetch
      - snapd
      - docker
      - exa
      - bat
    state: present

- name: Install Vim
  become: true
  package:
    name:
      - vim
      - neovim
    state: present

- name: Install Python
  become: true
  package:
    name: 
      - python3
    state: present

- name: Copy Alias File
  copy:
    src: files/alias
    dest: "{{ home }}/.alias"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy BASH File
  copy:
    src: files/bash
    dest: "{{ home }}/.bashrc"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy TMUX config
  copy:
    src: files/tmux
    dest: "{{ home }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Make git Folder
  file:
    path: "{{ home }}/git/"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775

- name: Make NeoVIM Folder
  file:
    path: "{{ home }}/.config/nvim"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775

- name: Copy NeoVIM config
  copy:
    src: files/neovim
    dest: "{{ home }}/.config/nvim/init.vim"
    owner: "{{ user }}"
    group: "{{ user }}"
